# -----------------------------------------------------------------------------
# Author: Alejandro M. BERNARDIS
# Email: alejandro.bernardis at gmail.com
# -----------------------------------------------------------------------------
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: inventory
  annotations:
    image.openshift.io/triggers: |-
      [{
        "from":{
          "kind":"ImageStreamTag",
          "name":"inventory:latest"
        },
        "fieldPath":"spec.template.spec.containers[?(@.name==\"inventory\")].image",
        "pause":"false"
      }]
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 180
      containers:
        - name: inventory
          image: inventory:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: database
                  key: host
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: database
                  key: port
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: database
                  key: database
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database
                  key: password
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: inventory
                  key: tz
            - name: BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: inventory
                  key: base_url
            - name: PROXY_IPS
              valueFrom:
                configMapKeyRef:
                  name: inventory
                  key: proxy_ips
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: inventory
                  key: encryption_key
          readinessProbe:
            tcpSocket:
              port: 8080
          livenessProbe:
            tcpSocket:
              port: 8080
          resources:
            requests:
              cpu: 500m
              memory: 2048Mi
            limits:
              cpu: 2000m
              memory: 4096Mi
