---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ./service-account.yaml
  - ./service.yaml
  - ./stateful-set.yaml

labels:
  - pairs:
      app.openshift.io/runtime: mariadb
      asa.airflow.component: database
    includeSelectors: true

commonAnnotations:
  asa.airflow.component: database

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: database
    envs:
      - ./database.env
