# -----------------------------------------------------------------------------
# Author: Alejandro M. BERNARDIS
# Email: alejandro.bernardis at gmail.com
# -----------------------------------------------------------------------------
---
kind: Service
apiVersion: v1
metadata:
  name: database
spec:
  type: ClusterIP
  ports:
    - name: database
      port: 3306
      targetPort: 3306
      protocol: TCP
